import crypto from "crypto";
import pool from "../db/pool.js";


/* =========================================================
   HASH SESSION TOKEN
========================================================= */

function hashToken(token) {

    return crypto
        .createHash("sha256")
        .update(token, "utf8")
        .digest("hex");

}


/* =========================================================
   REQUIRE AUTHENTICATED SESSION
========================================================= */

export async function requireAuth(
    req,
    res,
    next
) {

    try {

        /* =====================================================
           AUTHORIZATION HEADER
        ===================================================== */

        const authorization =
            req.headers.authorization;


        if (
            typeof authorization !== "string" ||
            !authorization.startsWith("Bearer ")
        ) {

            return res.status(401).json({
                success: false,
                code: "AUTH_REQUIRED",
                message: "Authentication required."
            });

        }


        /* =====================================================
           GET TOKEN
        ===================================================== */

        const token =
            authorization
                .slice(7)
                .trim();


        if (!token) {

            return res.status(401).json({
                success: false,
                code: "INVALID_SESSION",
                message: "Invalid session."
            });

        }


        /*
           Session tokens generated by the authentication
           service should be sufficiently long.

           This prevents obviously malformed requests from
           reaching PostgreSQL.
        */

        if (
            token.length < 32 ||
            token.length > 512
        ) {

            return res.status(401).json({
                success: false,
                code: "INVALID_SESSION",
                message: "Invalid session."
            });

        }


        /* =====================================================
           HASH TOKEN
        ===================================================== */

        const tokenHash =
            hashToken(token);


        /* =====================================================
           FIND SESSION + USER
        ===================================================== */

        const result =
            await pool.query(
                `
                SELECT

                    s.id AS session_id,

                    s.user_id,

                    s.expires_at,

                    u.id,

                    u.telegram_id,

                    u.username,

                    u.first_name,

                    u.last_name,

                    u.photo_url,

                    u.language_code,

                    u.is_premium,

                    u.coins,

                    u.today_coins,

                    u.games_played,

                    u.easy_games,

                    u.medium_games,

                    u.hard_games,

                    u.easy_level,

                    u.medium_level,

                    u.hard_level,

                    u.lives,

                    u.last_life_at,

                    u.daily_streak,

                    u.last_daily_claim,

                    u.is_blocked,

                    u.created_at,

                    u.updated_at,

                    u.last_seen_at

                FROM auth_sessions s

                INNER JOIN users u
                    ON u.id = s.user_id

                WHERE s.token_hash = $1

                  AND s.expires_at > NOW()

                LIMIT 1
                `,
                [
                    tokenHash
                ]
            );


        /* =====================================================
           SESSION NOT FOUND
        ===================================================== */

        if (
            result.rowCount === 0
        ) {

            return res.status(401).json({
                success: false,
                code: "INVALID_SESSION",
                message: "Session expired or invalid."
            });

        }


        const sessionUser =
            result.rows[0];


        /* =====================================================
           BLOCKED ACCOUNT
        ===================================================== */

        if (
            sessionUser.is_blocked === true
        ) {

            return res.status(403).json({
                success: false,
                code: "ACCOUNT_BLOCKED",
                message: "Account blocked."
            });

        }


        /* =====================================================
           UPDATE SESSION LAST USED
        ===================================================== */

        await pool.query(
            `
            UPDATE auth_sessions

            SET last_used_at = NOW()

            WHERE id = $1
            `,
            [
                sessionUser.session_id
            ]
        );


        /* =====================================================
           UPDATE USER LAST SEEN
        ===================================================== */

        await pool.query(
            `
            UPDATE users

            SET last_seen_at = NOW()

            WHERE id = $1
            `,
            [
                sessionUser.user_id
            ]
        );


        /* =====================================================
           BUILD AUTHENTICATED USER
        ===================================================== */

        req.user = {

            /*
               Both names are intentionally provided.

               Existing routes may use:
                   req.user.id

               Other routes may use:
                   req.user.user_id
            */

            id:
                sessionUser.user_id,

            user_id:
                sessionUser.user_id,

            session_id:
                sessionUser.session_id,

            telegram_id:
                sessionUser.telegram_id,

            username:
                sessionUser.username,

            first_name:
                sessionUser.first_name,

            last_name:
                sessionUser.last_name,

            photo_url:
                sessionUser.photo_url,

            language_code:
                sessionUser.language_code,

            is_premium:
                sessionUser.is_premium,

            coins:
                sessionUser.coins,

            today_coins:
                sessionUser.today_coins,

            games_played:
                sessionUser.games_played,

            easy_games:
                sessionUser.easy_games,

            medium_games:
                sessionUser.medium_games,

            hard_games:
                sessionUser.hard_games,

            easy_level:
                sessionUser.easy_level,

            medium_level:
                sessionUser.medium_level,

            hard_level:
                sessionUser.hard_level,

            lives:
                sessionUser.lives,

            last_life_at:
                sessionUser.last_life_at,

            daily_streak:
                sessionUser.daily_streak,

            last_daily_claim:
                sessionUser.last_daily_claim,

            is_blocked:
                sessionUser.is_blocked

        };


        /* =====================================================
           CONTINUE
        ===================================================== */

        return next();


    } catch (error) {

        console.error(
            "Auth middleware error:",
            error
        );


        return res.status(500).json({
            success: false,
            code: "AUTH_ERROR",
            message: "Authentication error."
        });

    }

}
